# qgmlwy-layout
keycode  16 = q
keycode  17 = g
keycode  18 = m
keycode  19 = l
keycode  20 = w
keycode  21 = y
keycode  22 = f
keycode  23 = u
keycode  24 = b
keycode  25 = semicolon         colon 
#
keycode  30 = d 
keycode  31 = s
keycode  32 = t
keycode  33 = n
keycode  34 = r
keycode  35 = i
keycode  36 = a
keycode  37 = e
keycode  38 = o
#
keycode  44 = z
keycode  45 = x
keycode  46 = c
keycode  47 = v
keycode  48 = j
keycode  49 = k
keycode  50 = p
#
include "compose"
