cp ~/.config/awesome/rc.lua ~/repo/archBak/config/awesome/rc.lua
cp ~/.bashrc ~/repo/archBak/config/shell/.bashrc
cp ~/.xinitrc ~/repo/archBak/config/shell/.xinitrc
cp ~/.Xresources ~/repo/archBak/config/shell/.Xresources
cp ~/.bash_profile ~/repo/archBak/config/shell/.bash_profile
cp ~/.emacs ~/repo/archBak/config/emacs/.emacs
cp ~/.mplayer/config ~/repo/archBak/config/mplayer/config
cp /etc/vimrc ~/repo/archBak/config/vim/vimrc
cp ~/.xpdfrc ~/repo/archBak/config/xpdf/.xpdfrc
